"""
Python Code Generation Tools
"""

from genericsuite_codegen.utilities.app_logger import (
    log_error,
)
from genericsuite_codegen.agent.types import (
    PythonCodeResult,
)
from genericsuite_codegen.agent.tool_knowledge_base import KnowledgeBaseTool


DEBUG = True


class PythonCodeGenerator:
    """
    Python code generator for GenericSuite applications.

    Generates Langchain Tools, MCP Tools, and other Python code
    following GenericSuite patterns and best practices.
    """

    def __init__(self, kb_tool: KnowledgeBaseTool):
        """Initialize the Python code generator."""
        self.kb_tool = kb_tool
        self._load_templates()

    def _load_templates(self) -> None:
        """Load code templates and patterns."""
        # Langchain Tool template
        self.langchain_tool_template = '''"""
{tool_name} - Langchain Tool for GenericSuite

{description}
"""

from typing import Dict, Any, Optional, List
from langchain.tools import BaseTool
from pydantic import BaseModel, Field
import logging

logger = logging.getLogger(__name__)


class {tool_class_name}Input(BaseModel):
    """Input schema for {tool_name}."""
    {input_fields}


class {tool_class_name}(BaseTool):
    """
    {tool_description}

    This tool integrates with GenericSuite applications to provide
    {functionality_description}
    """

    name: str = "{tool_name}"
    description: str = "{tool_description}"
    args_schema: type[BaseModel] = {tool_class_name}Input

    def _run(self, {run_parameters}) -> str:
        """
        Execute the {tool_name} operation.

        Args:
            {run_args_docs}

        Returns:
            str: Result of the operation.
        """
        try:
            logger.info(f"Executing {tool_name} with parameters: "
                        f"{{{run_parameters}}}")

            # Implementation logic
            {implementation_code}

            return result

        except Exception as e:
            logger.error(f"{tool_name} execution failed: {{e}}")
            raise RuntimeError(f"{tool_name} failed: {{e}}")

    async def _arun(self, {run_parameters}) -> str:
        """Async version of _run."""
        return self._run({run_parameters})


# Tool instance for registration
{tool_instance_name} = {tool_class_name}()
'''

        # MCP Tool template
        self.mcp_tool_template = '''"""
{tool_name} - MCP Tool for GenericSuite

{description}
"""

from typing import Dict, Any, Optional, List, Sequence
from fastmcp import FastMCP
from pydantic import BaseModel, Field
import logging
import datetime

logger = logging.getLogger(__name__)


class {tool_class_name}Args(BaseModel):
    """Arguments schema for {tool_name}."""
    {args_fields}


# Initialize FastMCP server
mcp = FastMCP("{tool_name}")


@mcp.tool()
def {tool_function_name}({function_parameters}) -> Dict[str, Any]:
    """
    {tool_description}

    Args:
        {function_args_docs}

    Returns:
        Dict[str, Any]: Result of the operation.
    """
    try:
        logger.info(f"Executing {tool_name} MCP tool")

        # Validate arguments
        args = {tool_class_name}Args({args_validation})

        # Implementation logic
        {implementation_code}

        return {{
            "success": True,
            "result": result,
            "tool": "{tool_name}",
            "timestamp": datetime.datetime.now(datetime.UTC).isoformat()
        }}

    except Exception as e:
        logger.error(f"{tool_name} MCP tool failed: {{e}}")
        return {{
            "success": False,
            "error": str(e),
            "tool": "{tool_name}",
            "timestamp": datetime.datetime.now(datetime.UTC).isoformat()
        }}


@mcp.resource("urn:{tool_name}:info")
def get_{tool_function_name}_info() -> str:
    """Get information about the {tool_name} tool."""
    return f"""
{tool_name} MCP Tool

{tool_description}

Usage:
- Call the {tool_function_name} function with appropriate parameters
- Returns structured results with success/error status
- Integrates with GenericSuite applications

Generated by GenericSuite CodeGen
"""


if __name__ == "__main__":
    # Run the MCP server
    mcp.run()
'''

        # Utility function template
        self.utility_template = '''"""
{function_name} - GenericSuite Utility Function

{description}
"""

from typing import Dict, Any, Optional, List, Union
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


def {function_name}({function_parameters}) -> {return_type}:
    """
    {function_description}

    Args:
        {function_args_docs}

    Returns:
        {return_type}: {return_description}

    Raises:
        ValueError: If input parameters are invalid.
        RuntimeError: If operation fails.
    """
    try:
        logger.debug(f"Executing {function_name} with parameters: "
                     f"{{{function_parameters}}}")

        # Input validation
        {validation_code}

        # Implementation logic
        {implementation_code}

        logger.debug(f"{function_name} completed successfully")
        return result

    except ValueError as e:
        logger.error(f"Invalid parameters for {function_name}: {{e}}")
        raise
    except Exception as e:
        logger.error(f"{function_name} execution failed: {{e}}")
        raise RuntimeError(f"{function_name} failed: {{e}}")


# Helper functions
{helper_functions}
'''

    def generate_langchain_tool(self, requirements: str, tool_name: str
                                ) -> PythonCodeResult:
        """
        Generate a Langchain Tool following ExampleApp patterns.

        Args:
            requirements: Requirements for the tool.
            tool_name: Name of the tool.

        Returns:
            PythonCodeResult: Generated Langchain tool code.
        """
        try:
            # Get relevant context for Langchain tools
            context, sources, raw_results = \
                self.kb_tool.get_context_for_generation(
                    query=f"GenericSuite Langchain tool {requirements}",
                    max_context_length=None,
                    file_type_filter="py"
                )

            # Parse requirements and generate code components
            tool_class_name = self._to_class_name(tool_name)
            tool_instance_name = self._to_instance_name(tool_name)

            # Generate input fields
            input_fields = self._generate_input_fields(requirements)

            # Generate implementation code
            implementation_code = self._generate_implementation_code(
                requirements, "langchain")

            # Generate run parameters
            run_parameters = self._generate_run_parameters(input_fields)

            # Format the template
            code = self.langchain_tool_template.format(
                tool_name=tool_name,
                description=f"Langchain tool for {requirements}",
                tool_class_name=tool_class_name,
                tool_instance_name=tool_instance_name,
                tool_description="GenericSuite Langchain tool that "
                                 f"{requirements}",
                functionality_description=requirements.lower(),
                input_fields=input_fields,
                run_parameters=run_parameters,
                run_args_docs=self._generate_args_docs(input_fields),
                implementation_code=implementation_code
            )

            # Generate imports
            imports = [
                "from langchain.tools import BaseTool",
                "from pydantic import BaseModel, Field",
                "from typing import Dict, Any, Optional, List",
                "import logging"
            ]

            # Generate usage example
            usage_example = self._generate_langchain_usage_example(
                tool_class_name, tool_name)

            # Generate test code
            test_code = self._generate_test_code(
                tool_name, "langchain") if True else None

            # Generate documentation
            documentation = self._generate_documentation(
                tool_name, "langchain", requirements)

            return PythonCodeResult(
                code=code,
                code_type="langchain_tool",
                imports=imports,
                usage_example=usage_example,
                test_code=test_code,
                documentation=documentation,
                sources=sources
            )

        except Exception as e:
            log_error(f"Failed to generate Langchain tool: {e}")
            raise RuntimeError(f"Langchain tool generation failed: {e}")

    def generate_mcp_tool(self, requirements: str, tool_name: str
                          ) -> PythonCodeResult:
        """
        Generate an MCP Tool compatible with FastMCP framework.

        Args:
            requirements: Requirements for the tool.
            tool_name: Name of the tool.

        Returns:
            PythonCodeResult: Generated MCP tool code.
        """
        try:
            # Get relevant context for MCP tools
            context, sources, raw_results = \
                self.kb_tool.get_context_for_generation(
                    query=f"GenericSuite MCP tool FastMCP {requirements}",
                    max_context_length=None,
                    file_type_filter="py"
                )

            # Parse requirements and generate code components
            tool_class_name = self._to_class_name(tool_name)
            tool_function_name = self._to_function_name(tool_name)

            # Generate arguments fields
            args_fields = self._generate_args_fields(requirements)

            # Generate implementation code
            implementation_code = self._generate_implementation_code(
                requirements, "mcp")

            # Generate function parameters
            function_parameters = self._generate_function_parameters(
                args_fields)

            # Format the template
            code = self.mcp_tool_template.format(
                tool_name=tool_name,
                description=f"MCP tool for {requirements}",
                tool_class_name=tool_class_name,
                tool_function_name=tool_function_name,
                tool_description=f"GenericSuite MCP tool that {requirements}",
                args_fields=args_fields,
                function_parameters=function_parameters,
                function_args_docs=self._generate_function_args_docs(
                    args_fields),
                args_validation=self._generate_args_validation(args_fields),
                implementation_code=implementation_code
            )

            # Generate imports
            imports = [
                "from fastmcp import FastMCP",
                "from pydantic import BaseModel, Field",
                "from typing import Dict, Any, Optional, List, Sequence",
                "from datetime import datetime",
                "import logging"
            ]

            # Generate usage example
            usage_example = self._generate_mcp_usage_example(
                tool_function_name, tool_name)

            # Generate test code
            test_code = self._generate_test_code(
                tool_name, "mcp") if True else None

            # Generate documentation
            documentation = self._generate_documentation(
                tool_name, "mcp", requirements)

            return PythonCodeResult(
                code=code,
                code_type="mcp_tool",
                imports=imports,
                usage_example=usage_example,
                test_code=test_code,
                documentation=documentation,
                sources=sources
            )

        except Exception as e:
            log_error(f"Failed to generate MCP tool: {e}")
            raise RuntimeError(f"MCP tool generation failed: {e}")

    def generate_utility_function(self, requirements: str, function_name: str
                                  ) -> PythonCodeResult:
        """
        Generate a utility function for GenericSuite applications.

        Args:
            requirements: Requirements for the function.
            function_name: Name of the function.

        Returns:
            PythonCodeResult: Generated utility function code.
        """
        try:
            # Get relevant context
            context, sources, raw_results = \
                self.kb_tool.get_context_for_generation(
                    query=f"GenericSuite utility function {requirements}",
                    max_context_length=None,
                    file_type_filter="py"
                )

            # Generate function components
            function_parameters = self._generate_utility_parameters(
                requirements)
            return_type = self._determine_return_type(requirements)

            # Generate implementation code
            implementation_code = self._generate_implementation_code(
                requirements, "utility")
            validation_code = self._generate_validation_code(requirements)
            helper_functions = self._generate_helper_functions(requirements)

            # Format the template
            code = self.utility_template.format(
                function_name=function_name,
                description=f"Utility function for {requirements}",
                function_parameters=function_parameters,
                return_type=return_type,
                function_description="GenericSuite utility function that "
                                     f"{requirements}",
                function_args_docs=self._generate_utility_args_docs(
                    function_parameters),
                return_description=f"Result of {requirements}",
                validation_code=validation_code,
                implementation_code=implementation_code,
                helper_functions=helper_functions
            )

            # Generate imports
            imports = [
                "from typing import Dict, Any, Optional, List, Union",
                "from datetime import datetime",
                "import logging"
            ]

            # Generate usage example
            usage_example = self._generate_utility_usage_example(function_name)

            # Generate test code
            test_code = self._generate_test_code(
                function_name, "utility") if True else None

            # Generate documentation
            documentation = self._generate_documentation(
                function_name, "utility", requirements)

            return PythonCodeResult(
                code=code,
                code_type="utility",
                imports=imports,
                usage_example=usage_example,
                test_code=test_code,
                documentation=documentation,
                sources=sources
            )

        except Exception as e:
            log_error(f"Failed to generate utility function: {e}")
            raise RuntimeError(f"Utility function generation failed: {e}")

    # Helper methods for code generation

    def _to_class_name(self, name: str) -> str:
        """Convert name to PascalCase class name."""
        return ''.join(word.capitalize() for word in
                       name.replace('_', ' ').replace('-', ' ').split())

    def _to_instance_name(self, name: str) -> str:
        """Convert name to snake_case instance name."""
        return name.lower().replace(' ', '_').replace('-', '_')

    def _to_function_name(self, name: str) -> str:
        """Convert name to snake_case function name."""
        return name.lower().replace(' ', '_').replace('-', '_')

    def _generate_input_fields(self, requirements: str) -> str:
        """Generate input fields for Langchain tools."""
        # Basic field generation based on requirements
        fields = []

        if "query" in requirements.lower() or "search" in requirements.lower():
            fields.append(
                'query: str = Field(description="Search query or input text")')

        if "limit" in requirements.lower() or "count" in requirements.lower():
            fields.append(
                'limit: int = Field(default=10, description="Maximum number'
                ' of results")')

        if "filter" in requirements.lower():
            fields.append(
                'filter_type: Optional[str] = Field(default=None, '
                'description="Optional filter criteria")')

        if not fields:
            fields.append(
                'input_data: str = Field(description="Input data for'
                ' processing")')

        return '\n    '.join(fields)

    def _generate_args_fields(self, requirements: str) -> str:
        """Generate argument fields for MCP tools."""
        return self._generate_input_fields(requirements)  # Same logic for now

    def _generate_implementation_code(self, requirements: str, code_type: str
                                      ) -> str:
        """Generate implementation code based on requirements."""
        if "search" in requirements.lower():
            return '''# Perform search operation
            search_results = perform_search(query, limit)
            result = format_search_results(search_results)'''
        elif "process" in requirements.lower():
            return '''# Process input data
            processed_data = process_input(input_data)
            result = format_output(processed_data)'''
        elif "generate" in requirements.lower():
            return '''# Generate output based on input
            generated_content = generate_content(input_data)
            result = validate_and_format(generated_content)'''
        else:
            return '''# Implement the main functionality
            # TODO: Add specific implementation based on requirements
            result = f"Processed: {input_data}"'''

    def _generate_run_parameters(self, input_fields: str) -> str:
        """Generate run method parameters from input fields."""
        # Extract field names from input_fields
        lines = input_fields.split('\n')
        params = []
        for line in lines:
            if ':' in line:
                field_name = line.strip().split(':')[0]
                params.append(field_name)
        return ', '.join(params)

    def _generate_function_parameters(self, args_fields: str) -> str:
        """Generate function parameters from args fields."""
        return self._generate_run_parameters(args_fields)

    def _generate_utility_parameters(self, requirements: str) -> str:
        """Generate parameters for utility functions."""
        if "data" in requirements.lower():
            return "data: Dict[str, Any], options: Optional[Dict[str, Any]]"
            " = None"
        elif "text" in requirements.lower():
            return "text: str, config: Optional[Dict[str, Any]] = None"
        else:
            return "input_value: Any, **kwargs"

    def _generate_args_docs(self, input_fields: str) -> str:
        """Generate argument documentation."""
        return "Parameters extracted from input schema"

    def _generate_function_args_docs(self, args_fields: str) -> str:
        """Generate function argument documentation."""
        return self._generate_args_docs(args_fields)

    def _generate_utility_args_docs(self, parameters: str) -> str:
        """Generate utility function argument documentation."""
        return "Function parameters as specified"

    def _generate_args_validation(self, args_fields: str) -> str:
        """Generate argument validation code."""
        # Extract field names and create validation dict
        lines = args_fields.split('\n')
        validations = []
        for line in lines:
            if ':' in line:
                field_name = line.strip().split(':')[0]
                validations.append(f"{field_name}={field_name}")
        return ', '.join(validations)

    def _determine_return_type(self, requirements: str) -> str:
        """Determine return type based on requirements."""
        if "list" in requirements.lower() or "results" in requirements.lower():
            return "List[Dict[str, Any]]"
        elif "dict" in requirements.lower() or \
                "object" in requirements.lower():
            return "Dict[str, Any]"
        elif "bool" in requirements.lower() or "check" in requirements.lower():
            return "bool"
        else:
            return "str"

    def _generate_validation_code(self, requirements: str) -> str:
        """Generate input validation code."""
        return '''if not input_value:
            raise ValueError("Input value cannot be empty")'''

    def _generate_helper_functions(self, requirements: str) -> str:
        """Generate helper functions."""
        return '''
def format_output(data: Any) -> str:
    """Format output data for return."""
    return str(data)


def validate_input(data: Any) -> bool:
    """Validate input data."""
    return data is not None
'''

    def _generate_langchain_usage_example(self, class_name: str,
                                          tool_name: str) -> str:
        """Generate usage example for Langchain tool."""
        return f'''# Usage example for {tool_name}
from langchain.agents import initialize_agent, AgentType
from langchain.llms import OpenAI

# Initialize the tool
tool = {class_name}()

# Use with an agent
llm = OpenAI(temperature=0)
agent = initialize_agent([tool], llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)

# Execute
result = agent.run("Use {tool_name} to process some data")
print(result)
'''

    def _generate_mcp_usage_example(self, function_name: str, tool_name: str
                                    ) -> str:
        """Generate usage example for MCP tool."""
        return f'''# Usage example for {tool_name} MCP tool

# Run the MCP server
python {function_name}.py

# Or integrate with MCP client
from mcp_client import MCPClient

client = MCPClient("http://localhost:8070")
result = client.call_tool("{function_name}", {{"input_data": "test"}})
print(result)
'''

    def _generate_utility_usage_example(self, function_name: str) -> str:
        """Generate usage example for utility function."""
        return f'''# Usage example for {function_name}

from your_module import {function_name}

# Basic usage
result = {function_name}("input data")
print(result)

# With options
result = {function_name}("input data", {{"option": "value"}})
print(result)
'''

    def _generate_test_code(self, name: str, code_type: str) -> str:
        """Generate unit test code."""
        test_name = self._to_function_name(name)

        return f'''"""
Unit tests for {name} {code_type}
"""

import unittest
from unittest.mock import Mock, patch
import pytest

from your_module import {name}


class Test{self._to_class_name(name)}(unittest.TestCase):
    """Test cases for {name}."""

    def setUp(self):
        """Set up test fixtures."""
        self.test_input = "test data"

    def test_{test_name}_success(self):
        """Test successful execution."""
        # Arrange
        expected_result = "expected output"

        # Act
        result = {name}(self.test_input)

        # Assert
        self.assertIsNotNone(result)
        self.assertIsInstance(result, str)

    def test_{test_name}_invalid_input(self):
        """Test handling of invalid input."""
        # Act & Assert
        with self.assertRaises(ValueError):
            {name}("")

    def test_{test_name}_error_handling(self):
        """Test error handling."""
        # This test would depend on specific implementation
        pass


if __name__ == "__main__":
    unittest.main()
'''

    def _generate_documentation(self, name: str, code_type: str,
                                requirements: str) -> str:
        """Generate comprehensive documentation."""
        return f'''# {name} - {code_type.title()}

## Overview
{name} is a GenericSuite {code_type} that {requirements}.

## Features
- Follows GenericSuite patterns and conventions
- Includes comprehensive error handling
- Provides detailed logging and monitoring
- Compatible with GenericSuite applications

## Installation
1. Copy the generated code to your project
2. Install required dependencies
3. Configure as needed for your application

## Usage
See the usage example in the generated code for implementation details.

## Testing
Run the included unit tests to verify functionality:
```bash
python -m pytest test_{self._to_function_name(name)}.py
```

## Integration
This {code_type} integrates with GenericSuite applications and follows
the framework's patterns for consistency and maintainability.

Generated by GenericSuite CodeGen
'''
