# deploy/docker-compose.yml

services:
  gscodegen-server:
    container_name: gscodegen-server
    image: gscodegen_python
    command: sh -c "bash /code/server-entrypoint.sh"
    volumes:
      - ../server:/code
      - ../mcp-server:/code/mcp-server
      - ../server/genericsuite_codegen:/code/mcp-server/genericsuite_codegen
      - ./server-entrypoint.sh:/code/server-entrypoint.sh
      - ./local_repo_files:/code/local_repo_files
      - ../.env:/code/.env
    environment:
      # Server environment variables
      - SERVER_PORT=${SERVER_PORT:-8000}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - APP_DOMAIN_NAME=${APP_DOMAIN_NAME}
      - APP_NAME=${APP_NAME}
      - SERVER_DEBUG=${SERVER_DEBUG}
      - MONGODB_URI=${MONGODB_URI}
      - REMOTE_REPO_URL=${REMOTE_REPO_URL}
      - LOCAL_REPO_DIR=${LOCAL_REPO_DIR}
      - HF_TOKEN=${HF_TOKEN}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_API=${LLM_API}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS}
      - LLM_TOP_P=${LLM_TOP_P}
      - LLM_TOP_K=${LLM_TOP_K}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      # MCP Server environment variables
      - MCP_API_KEY=${MCP_API_KEY}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8070}
      - MCP_SERVER_HOST=${MCP_SERVER_HOST:-0.0.0.0}
    ports: ["8000:8000", "8070:8070"]
    networks:
      - my_shared_network
    restart: unless-stopped

  gscodegen-client:
    container_name: gscodegen-client
    image: nginx:alpine
    volumes:
      - ../ui/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - UI_PORT=${UI_PORT:-3000}
      - UI_SECURE_PORT=${UI_SECURE_PORT:-3001}
      - UI_APP_DOMAIN_NAME=${APP_DOMAIN_NAME}
      - UI_API_BASE_URL=${UI_API_BASE_URL}
      - UI_APP_SUBDIR=${UI_APP_SUBDIR}
      - UI_DEBUG=${UI_DEBUG}
    ports: ["3000:80", "3001:443"]
    depends_on: [gscodegen-server]
    networks:
      - my_shared_network
    restart: unless-stopped

  mongo:
    container_name: gscodegen-mongo-db
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - my_shared_network

  mongo-express:
    container_name: gscodegen-mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on: [mongo]
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true